// Single source of truth for every artwork on the site.
// Edit the human-friendly data in artworks.json (or run `npm run art` after
// dropping new images into public/images — it scaffolds new entries for you).
import data from "./artworks.json";
import { imageAspects } from "./imageAspects";

export type Category = "teacher" | "adult" | "child";

export type Artwork = {
  image: string;
  title: string;
  artist: string;
  medium: string;
  size: string;
  category: Category;
};

export const artworks = data as Artwork[];

// Display order + copy for each showcase. Descriptions are safe to edit freely.
export const categoryOrder: Category[] = ["teacher", "adult", "child"];

export const categoryMeta: Record<Category, { label: string; description: string }> = {
  teacher: {
    label: "Teacher Showcase",
    description: "Kerala-inspired works celebrating landscapes, festivals, and devotional art.",
  },
  adult: {
    label: "Adult Student Showcase",
    description: "Beginners and returning artists bringing their own ideas to life.",
  },
  child: {
    label: "Kid Student Showcase",
    description: "Young artists building skills and confidence—one colorful piece at a time.",
  },
};

export function worksByCategory(category: Category): Artwork[] {
  return artworks.filter((a) => a.category === category);
}

// Aspect ratio (width / height) used to reserve each slide's width in the
// carousels. Regenerated by `npm run art`; falls back to a portrait-ish default.
export function aspectOf(image: string): number {
  return imageAspects[image] ?? 1.4;
}

// An artwork is "complete" once all three credit fields are filled in.
// Incomplete ones still display — they just show what's available.
export function isComplete(a: Artwork): boolean {
  return Boolean(a.artist.trim() && a.medium.trim() && a.size.trim());
}

export function displayTitle(a: Artwork): string {
  return a.title.trim() || "Untitled";
}

// One-line credit under a title, e.g. "Gayathri Suresh · Oil on canvas · 24 × 36 in".
export function credit(a: Artwork): string {
  return [a.artist, a.medium, a.size]
    .map((p) => p.trim())
    .filter(Boolean)
    .join(" · ");
}
