// Single source of truth for every artwork on the site.
// Edit the human-friendly data in artworks.json (or run `npm run art` after
// dropping new images into public/images — it scaffolds new entries for you).
import data from "./artworks.json";
import { imageAspects } from "./imageAspects";

export type Category = "teacher" | "adult" | "child";

export type Artwork = {
  image: string;
  title: string;
  artist: string;
  medium: string;
  size: string;
  category: Category;
  // Optional free-form caption. When set, it's shown verbatim under the title
  // (overriding the artist/medium/size credit). Handy for one-line descriptions
  // like "Kerala Mural Painting - Acrylic on Canvas - Gayathri Suresh".
  description?: string;
};

export const artworks = data as Artwork[];

// Display order + copy for each showcase. Descriptions are safe to edit freely.
export const categoryOrder: Category[] = ["teacher", "adult", "child"];

export const categoryMeta: Record<Category, { label: string; description: string }> = {
  teacher: {
    label: "Teacher Showcase",
    description: "",
  },
  adult: {
    label: "Adult Student Showcase",
    description: "",
  },
  child: {
    label: "Kid Student Showcase",
    description: "",
  },
};

export function worksByCategory(category: Category): Artwork[] {
  return artworks.filter((a) => a.category === category);
}

// Stable, unique URL slug for an artwork's detail page, derived from its image
// filename (e.g. "/images/artwork-12.jpg" -> "artwork-12").
export function slugFor(a: Artwork): string {
  return a.image.replace(/^\/images\//, "").replace(/\.[^.]+$/, "");
}

export function bySlug(slug: string): Artwork | undefined {
  return artworks.find((a) => slugFor(a) === slug);
}

// Aspect ratio (width / height) used to reserve each slide's width in the
// carousels. Regenerated by `npm run art`; falls back to a portrait-ish default.
export function aspectOf(image: string): number {
  return imageAspects[image] ?? 1.4;
}

// An artwork is "complete" when it has a description, or all three credit
// fields. Incomplete ones still display — they just show what's available.
export function isComplete(a: Artwork): boolean {
  if (a.description?.trim()) return true;
  return Boolean(a.artist.trim() && a.medium.trim() && a.size.trim());
}

export function displayTitle(a: Artwork): string {
  return a.title.trim() || "Untitled";
}

// One-line caption under a title. A free-form `description` wins; otherwise
// build it from artist/medium/size, e.g. "Gayathri Suresh · Oil on canvas · 24 × 36 in".
export function credit(a: Artwork): string {
  if (a.description?.trim()) return a.description.trim();
  return [a.artist, a.medium, a.size]
    .map((p) => p.trim())
    .filter(Boolean)
    .join(" · ");
}
