// Radiant Hues — art sync helper.
//
// Run:  npm run art
//
// For a non-technical editor the whole "add a painting" flow becomes:
//   1. Drop the image file into  public/images/  (name it artwork-<something>).
//   2. Run  npm run art
//   3. Open  src/content/artworks.json  and fill in the blank title / artist /
//      medium / size the script added for you.
//
// The script never overwrites details you've typed. It only:
//   • measures each image and regenerates src/content/imageAspects.ts
//   • adds a blank entry for any new artwork-* image
//   • prints a checklist of images still missing artist / medium / size.
//
// No dependencies, no API keys — dimensions are read straight from the file headers.

import { readFileSync, writeFileSync, readdirSync } from "node:fs";
import { fileURLToPath } from "node:url";
import { dirname, join, extname } from "node:path";
import { watermarkAll } from "./watermark.mjs";

// Bake the @RadiantHues watermark into any new images first, so everything the
// site serves is protected. (Idempotent — already-watermarked images are skipped.)
await watermarkAll();

const __dirname = dirname(fileURLToPath(import.meta.url));
const root = join(__dirname, "..");
const imagesDir = join(root, "public", "images");
const aspectsFile = join(root, "src", "content", "imageAspects.ts");
const artworksFile = join(root, "src", "content", "artworks.json");

// --- image dimension readers (JPEG / PNG / WebP), zero dependencies ----------

function jpegSize(buf) {
  let off = 2; // skip SOI (0xFFD8)
  while (off + 9 < buf.length) {
    if (buf[off] !== 0xff) {
      off++;
      continue;
    }
    const marker = buf[off + 1];
    off += 2;
    // Start-Of-Frame markers carry the dimensions.
    if (marker >= 0xc0 && marker <= 0xcf && marker !== 0xc4 && marker !== 0xc8 && marker !== 0xcc) {
      const height = buf.readUInt16BE(off + 3);
      const width = buf.readUInt16BE(off + 5);
      return { width, height };
    }
    if (marker === 0xd8 || marker === 0xd9 || (marker >= 0xd0 && marker <= 0xd7)) continue;
    off += buf.readUInt16BE(off); // skip this segment
  }
  return null;
}

function pngSize(buf) {
  return { width: buf.readUInt32BE(16), height: buf.readUInt32BE(20) };
}

function webpSize(buf) {
  const fmt = buf.toString("ascii", 12, 16);
  if (fmt === "VP8 ") {
    return { width: buf.readUInt16LE(26) & 0x3fff, height: buf.readUInt16LE(28) & 0x3fff };
  }
  if (fmt === "VP8L") {
    const b0 = buf[21], b1 = buf[22], b2 = buf[23], b3 = buf[24];
    return {
      width: 1 + (((b1 & 0x3f) << 8) | b0),
      height: 1 + (((b3 & 0x0f) << 10) | (b2 << 2) | ((b1 & 0xc0) >> 6)),
    };
  }
  if (fmt === "VP8X") {
    return {
      width: 1 + (buf[24] | (buf[25] << 8) | (buf[26] << 16)),
      height: 1 + (buf[27] | (buf[28] << 8) | (buf[29] << 16)),
    };
  }
  return null;
}

function readSize(file) {
  const buf = readFileSync(file);
  const ext = extname(file).toLowerCase();
  if (ext === ".jpg" || ext === ".jpeg") return jpegSize(buf);
  if (ext === ".png") return pngSize(buf);
  if (ext === ".webp") return webpSize(buf);
  return null;
}

// --- main --------------------------------------------------------------------

const files = readdirSync(imagesDir)
  .filter((f) => /\.(jpe?g|png|webp)$/i.test(f))
  .sort();

// 1) Measure every image and regenerate imageAspects.ts
const aspects = {};
for (const f of files) {
  const size = readSize(join(imagesDir, f));
  if (!size || !size.width || !size.height) {
    console.warn(`  ! could not read dimensions for ${f} — skipping`);
    continue;
  }
  aspects[`/images/${f}`] = Number((size.width / size.height).toFixed(4));
}

const aspectBody = Object.keys(aspects)
  .sort()
  .map((k) => `  "${k}": ${aspects[k]},`)
  .join("\n");

writeFileSync(
  aspectsFile,
  `// Auto-generated by \`npm run art\` — do not edit by hand.\n` +
    `// Aspect ratio (width / height) for each image, so carousels reserve the right width.\n` +
    `export const imageAspects: Record<string, number> = {\n${aspectBody}\n};\n`,
);

// 2) Scaffold artworks.json for any new artwork-* image (details left blank)
const artworks = JSON.parse(readFileSync(artworksFile, "utf8"));
const known = new Set(artworks.map((a) => a.image));
const added = [];

for (const f of files) {
  if (!f.startsWith("artwork-")) continue; // portraits etc. aren't gallery art
  const image = `/images/${f}`;
  if (known.has(image)) continue;
  artworks.push({ image, title: "", artist: "", medium: "", size: "", category: "teacher" });
  added.push(image);
}

if (added.length) {
  writeFileSync(artworksFile, JSON.stringify(artworks, null, 2) + "\n");
}

// 3) Report
const incomplete = artworks.filter(
  (a) => !(a.description?.trim() || (a.artist?.trim() && a.medium?.trim() && a.size?.trim())),
);

console.log(`\nRadiant Hues art sync`);
console.log(`  images measured : ${Object.keys(aspects).length}`);
console.log(`  artworks total  : ${artworks.length}`);
if (added.length) {
  console.log(`  new scaffolds   : ${added.length}`);
  added.forEach((i) => console.log(`      + ${i}  (category defaulted to "teacher")`));
}
if (incomplete.length) {
  console.log(`\n  Needs artist / medium / size — edit src/content/artworks.json:`);
  incomplete.forEach((a) => console.log(`      • ${a.image}`));
} else {
  console.log(`\n  All artworks have full credits. `);
}
console.log("");
